# make
#
CC = gcc
CFLAGS = -march=athlon64 -msse -msse2 -msse3 -m3dnow -mmmx -mfpmath=sse,387 -fpic -O3 -ftree-vectorize -std=gnu99 -fgnu89-inline -w -fopenmp
SHFLAG = -shared
HDIR = /usr/share/R/include
LDIR = /usr/lib/R/lib
LIBS = -lR -lgomp -lpthread
input = *.c
obj = *.o
icav.so: $(obj)
	$(CC) -shared $(obj) -L$(LDIR) -o $@ $(LIBS)
$(obj):$(input)
	$(CC) -I$(HDIR) -L$(LDIR) $(CFLAGS) -c $(input)
clean:
	rm -rf *.o 